name: Resume Instances

on:
  schedule:
    - cron: '0 12 * * 1-5'
  workflow_dispatch:
jobs:
  start-instances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run start instances script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_PWD: ${{ secrets.CLIENT_PWD }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          python manage_instances.py start